### PR TITLE
Allow relative path for directory

### PR DESCRIPTION
**Pull request by rohit04saluja**
directory in _compiler_commands.json_
If the value is relative we resolve it from the root

This will help in VS Code integration. We open the root folder in **VS Code** and the directory value can be specified as related to the root folder. Thus the _compile_commnads.json_ can be committed to the code repository rather than having to build it every time code is pulled.

### CODE REVIEW

**Comment by rohit04saluja** [comment]
**Linked issue**: directory value as relative path in compile_commands.json #703 [issue](https://github.com/MaskRay/ccls/issues/703)

**Comment by MaskRay** [comment]
Currently `realPath` resolves the "directory" value relative to the current working directory. Is current working directory unchanged in VSCode?

**Comment by rohit04saluja** [comment]
Assuming that the current working directory refers to the workspace directory. I tried all possible combinations but it didn't work.

In CCLS logs, I can see that the files are resolved with relative paths only.
With this fix, it's resolved properly

**Comment by rohit04saluja** [comment]
Hi @MaskRay did you get time to check this?

**Comment by MaskRay** [comment]
I believe the problem is that your client does not chdir to the project root. Which client do you use?

**Comment by rohit04saluja** [comment]
I use VSCode

**Comment by rohit04saluja** [comment]
You were right @MaskRay . VSCode does not chdir to the project root It's always pointing to my home directory.

But since ccls is given a project path to initialize, won't be it good to chdir to the project path during initialization?

**Comment by rohit04saluja** [comment]
Need to be looked into from another angle

**Pull request closed without merging**
