### PR TITLE
using SIGSTOP (avoid interactive signal blocking)

### PR DESCRIPTION
**Pull request by amosbird**

### CODE REVIEW

**Comment by amosbird** [comment]
`SIGTSTP` only works for processes attached to a tty.  I'm not sure what term should be used.

**Comment by MaskRay** [comment]
`SIGSTOP` requires multiple `continue` commands in gdb while `SIGTSTP` only requires 1

**Comment by amosbird** [comment]
https://github.com/scottt/debugbreak looks better

**Comment by MaskRay** [comment]
I have changed the code to:
```
  const char* traceme = getenv("CCLS_TRACEME");
  if (traceme)
    raise(traceme[0] == 's' ? SIGSTOP : SIGTSTP);
```

`SIGTRAP` (debugbreak) only works when the process has been attached by a debugger, not in our use case.

**Comment by MaskRay** [comment]
LLVM also supports `__builtin_debugtrap` (`llvm.debugtrap`) for this purpose.

**Comment by amosbird** [comment]
Oh, OK. Good to know :)

**Pull request merged**
