### PR TITLE
add --version support

### PR DESCRIPTION
**Pull request by FirstLoveLife**
https://github.com/MaskRay/ccls/issues/334

### CODE REVIEW

**Comment by yssource** [comment]
why are you hard coding the version?

**Comment by FirstLoveLife** [comment]
@yssource I agree assigning it to a constexpr variable or leave it for cmake(like version.cmake.in)  are better choices, but it is not used anywhere else, so maybe it ain't that bad here.

**Comment by yssource** [comment]
@FirstLoveLife I suggest it may get the latest version from **cmake add_custom_command**, then pass it as constexpr variable.

add_custom_command may invoke some codes like the following.
`git show -s --format=%ci `git log -n1 --format=format:"%H"``

**Comment by MaskRay** [comment]
Ideally some cmake code runs `git describe --tags` and generates a macro definition in a `.hh` file which is included by `main.cc`......

**Comment by yssource** [comment]
There is no problem if the user compile ccls from the official git source.
But, it would be a problem if the user install it by different package installer. Such as pacman installer, yum installer etc, since there is no git commit.
So, I think it still have to get the version from a fixed value.

**Comment by madscientist** [comment]
I am working on the cmake version, related to issue #334  that I filed yesterday.

If you don't want me to work on that anymore it's fine, let me know.

**Pull request closed without merging**
