### PR TITLE
Fix for "Change containers of Query*::Def fields from std::vector to ccls::Vec" not building with MVS

### PR DESCRIPTION
**Pull request by SysRay**
I couldn't build the project with Visual Studio 2017 and the latest changes from "Change containers of Query*::Def fields from std::vector to ccls::Vec".  The compiler complaint about the missing constructors and operators.

### CODE REVIEW

**Comment by MaskRay** [comment]
> The compiler complaint about the missing constructors and operators.

Can you paste the build log?

**Comment by SysRay** [comment]
Of course:
[build.txt](https://github.com/MaskRay/ccls/files/2984530/build.txt)

...
C:\Program Files\LLVM\include\clang/Basic/Module.h(128): note: see reference to class template instantiation 'llvm::SmallSetVector<const clang::FileEntry *,2>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xmemory0(881): error C2280: 'std::pair<ccls::Usr,ccls::TypeDef<ccls::Vec>>::pair(const std::pair<ccls::Usr,ccls::TypeDef<ccls::Vec>> &)': attempting to reference a deleted function
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\utility(194): note: see declaration of 'std::pair<ccls::Usr,ccls::TypeDef<ccls::Vec>>::pair'
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\utility(194): note: 'std::pair<ccls::Usr,ccls::TypeDef<ccls::Vec>>::pair(const std::pair<ccls::Usr,ccls::TypeDef<ccls::Vec>> &)': function was implicitly deleted because a data member invokes a deleted or inaccessible function 'ccls::TypeDef<ccls::Vec>::TypeDef(const ccls::TypeDef<ccls::Vec> &)'
  f:\source\ccls\src\indexer.hh(226): note: 'ccls::TypeDef<ccls::Vec>::TypeDef(const ccls::TypeDef<ccls::Vec> &)': function was implicitly deleted because a data member invokes a deleted or inaccessible function 'ccls::Vec<ccls::Usr>::Vec(const ccls::Vec<ccls::Usr> &)'
  f:\source\ccls\src\utils.hh(154): note: 'ccls::Vec<ccls::Usr>::Vec(const ccls::Vec<ccls::Usr> &)': function was implicitly deleted because a data member invokes a deleted or inaccessible function 'std::unique_ptr<T [],std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)'
...

**Comment by MaskRay** [comment]
I think this is a bug in MSVC but we may have to work around it.

Do you know which line causes the issue?

If you delete those `emplace_back` calls from query.cc, does it compile?
```cpp
      r.funcs_removed.emplace_back(func.usr, Convert(func.def));
...
      r.funcs_def_update.emplace_back(it.first, Convert(func.def));

```

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/issues/327#issuecomment-474773200

**Comment by SysRay** [comment]
Same error with:
     r.funcs_removed.emplace_back(func.usr, Convert(func.def));
...
      r.funcs_def_update.emplace_back(it.first, Convert(func.def));

**Comment by MaskRay** [comment]
Thank you for reporting this. For that GCC bug I I'll go with:

```cpp
template <typename T> struct Vec {
  std::unique_ptr<T[]> a;
  int s = 0;
#if !(__clang__ || __GNUC__ > 7 || __GNUC__ == 7 && __GNUC_MINOR__ >= 4)
  // Work around a bug in GCC<7.4 that optional<IndexUpdate> would not be
  // construtible.
  Vec() = default;
  Vec(const Vec &o) : a(std::make_unique<T[]>(o.s)), s(o.s) {
    std::copy(o.a.get(), o.a.get() + o.s, a.get());
  }
  Vec(Vec &&) = default;
  Vec &operator=(Vec &&) = default;
  Vec(std::unique_ptr<T[]> a, int s) : a(std::move(a)), s(s) {}
#endif
  const T *begin() const { return a.get(); }
  T *begin() { return a.get(); }
  const T *end() const { return a.get() + s; }
  T *end() { return a.get() + s; }
  int size() const { return s; }
  const T &operator[](size_t i) const { return a.get()[i]; }
  T &operator[](size_t i) { return a.get()[i]; }
};
```

I guess the problem is around `src/pipeline.cc:664`

```
    bool indexed = false;
    for (int i = 20; i--;) {
      std::optional<IndexUpdate> update = on_indexed->TryPopFront();
```

Can you comment out this for loop and see it `pipeline.cc` compiles without the change to `Vec`?

**Comment by SysRay** [comment]
Still not working with the same error.

**Comment by MaskRay** [comment]
Can you be more specific what (MSVC 2017) doesn't work? gcc<7.4 cannot instantiate `std::optional<IndexUpdate>` without the user-defined ctors.

**Comment by SysRay** [comment]
Sorry, commenting out the for loop doesn't help.

The workaround is doing fine, therefore I closed the request.

**Comment by MaskRay** [comment]
`#if !(__clang__ || __GNUC__ > 7 || __GNUC__ == 7 && __GNUC_MINOR__ >= 4)`

If the compiler is clang, or the gcc version is greater or equal to 7.4, I think it doesn't need to user-defined ctors. `__clang__` is only defined by clang.

I would also like to know what is the minimum version of MSVC that can compile `pipeline.cc` without these user-defined ctors in `utils.hh`, and filter out those versions of MSVC.

**Pull request closed without merging**
