### PR TITLE
add flat option to ccls/inheritanceHierarchy 

### PR DESCRIPTION
**Pull request by amosbird**
useful for xref-like examination.

### CODE REVIEW

**Comment by MaskRay** [comment]
what's the difference between this and $ccls/inheritanceHierarchy ?

**Comment by amosbird** [comment]
It's used to export `xrefs` via `(lsp--locations-to-xref-items)` like commands `ccls/callers, ccls/vars` etc

**Comment by MaskRay** [comment]
Which do you think it resembles more, `$ccls/inheritanceHierarchy` or `$ccls/{base,derived}`? I wonder if it is possible to unify it with either existing interface, instead of creating (duplicating) a new one.

**Comment by amosbird** [comment]
`$ccls/{base,derived}`  . Well it's possible to traverse the entry-tree in elisp code but I feel that using a dedicated commands for that is much simpler and also provides support for other clients which doesn't have hierarchy interfaces.

**Comment by MaskRay** [comment]
I agree, that is why I asked LanguageClient-neovim author to support custom xref long ago https://github.com/autozimu/LanguageClient-neovim/issues/454 :)

I think this file should be unified with `$ccls/inheritanceHierarchy`.

**Comment by amosbird** [comment]
OK, is it fine to use `lsLocation` instead of `lsLocationEx` for xrefs?

**Comment by MaskRay** [comment]
The `flag` option has been added

**Pull request closed without merging**
